name: Android CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}  

jobs:
  build:
    name: Build APK


    runs-on: ubuntu-latest

    steps:

      - name: Cancel previous runs

        uses: styfle/cancel-workflow-action@0.10.0

        with:

          access_token: ${{ github.token }}
    - name: Clone repo

        uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
