name: Android CI

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    name: Build debug apk
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
    
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
  -name: Setup Ndk
  - uses: actions/checkout@v2
  - uses: nttld/setup-ndk@v1
    id: setup-ndk
    with:
      ndk-version: 24.0.8215888
      add-to-path: false
  - run: ./build.sh
    env:
      ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build debug apk
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload debug apk
        uses: actions/upload-artifact@v2
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
